import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import screenBreakpoints from '@/helpers/screenBreakpoints';
import PrimaryNavbar from '@/components/Header/PrimaryNavbar/PrimaryNavbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	// return (
	//   <html lang="en">
	//     <body className={inter.className}>{children}</body>
	//   </html>
	// )
	return (
		<html lang="en">
			<body>
				<div
					className="bg-primary text-neutral
		"
				>
					{/* <ScrollToTop /> */}
					<PrimaryNavbar className={`px-4 m-auto ${screenBreakpoints}`} />

					<main className="">{children}</main>
				</div>
			</body>
		</html>
	);
}
